"use strict";
const assert = require("assert");
const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");
const version = "jm-fluxo-comercial-v6-laudos-financeiro";
const css = fs.readFileSync(path.join(root, "css/style.css"), "utf8");
const app = fs.readFileSync(path.join(root, "js/app.js"), "utf8");
const mot = fs.readFileSync(path.join(root, "js/motorista.js"), "utf8");
const rel = fs.readFileSync(path.join(root, "relatorio.html"), "utf8");
assert(app.includes(version), "app.js sem versionamento V6");
assert(rel.includes(version), "relatorio.html sem versionamento V6");
assert(app.includes("Powered by thIAguinho Soluções Digitais"), "assinatura comercial ausente no app");
assert(css.includes("signature-footer::after") && css.includes("Powered by thIAguinho Soluções Digitais"), "rodapé comercial ausente no CSS");
assert(mot.includes('ctx.strokeStyle = "#111827"'), "assinatura do motorista não está em alto contraste");
assert(css.includes("filter: contrast(1.45") || css.includes("filter:contrast(1.65"), "assinatura/preview sem reforço de contraste");
assert(app.includes("finance-kpi-grid") && app.includes("Lucro previsto") && app.includes("Caixa realizado"), "KPIs financeiros executivos ausentes");
assert(rel.includes("signature-image") && rel.includes("Powered by thIAguinho Soluções Digitais"), "relatório público sem assinatura visual/rodapé V6");
console.log("commercial-v6 ok");
